# 3. 도형 그리기

## 빈 스케치북 만들기

In [4]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)
# imp[:] = (255, 255, 255)
# print(img)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 일부 영역 색칠

In [5]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)
img[100:200, 200:300] = (255,255,255)
print(img)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


## 직선
직선의 종류 (line type)

1. cv2.LINE_4 : 상하좌우 4 방향으로 연결된 선
1. cv2.LINE_8 : 대각선을 포함한 8방향으로 연결된 선(기본값)
1. cv2.LINE_AA : 부드러운 선 (anti-aliasing)

In [8]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR = (0, 255, 255)
THICKNESS = 3

cv2.line(img, (50, 100), (400,50), COLOR, THICKNESS, cv2.LINE_4)
cv2.line(img, (50, 200), (400,150), COLOR, THICKNESS, cv2.LINE_8)
cv2.line(img, (50, 300), (400,250), COLOR, THICKNESS, cv2.LINE_AA)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 원

In [10]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR = (0, 255, 255)
THICKNESS = 10
RADIUS = 50

cv2.circle(img, (200, 100), RADIUS, COLOR, THICKNESS, cv2.LINE_AA)
cv2.circle(img, (400, 100), RADIUS, COLOR, cv2.FILLED, cv2.LINE_AA)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 사각형

In [13]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR = (0, 255, 0)
THICKNESS = 10

cv2.rectangle(img, (100, 100), (200,200), COLOR, THICKNESS)
cv2.rectangle(img, (300, 100), (400,300), COLOR, cv2.FILLED)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 다각형

In [21]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR = (0, 0, 255)
THICKNESS = 3

pts1 = np.array([[100, 100], [200, 100], [100, 200]])
pts2 = np.array([[200, 100], [300, 100], [300, 200]])

# cv2.polylines(img, [pts1], True, COLOR, THICKNESS, cv2.LINE_AA)
# cv2.polylines(img, [pts2], True, COLOR, THICKNESS, cv2.LINE_AA)
cv2.polylines(img, [pts1, pts2], True, COLOR, THICKNESS, cv2.LINE_AA)

pts3 = np.array([[[100, 300], [200, 300], [100, 400]], [[200, 300], [300, 300], [300, 400]]])
cv2.fillPoly(img, pts3, COLOR, cv2.LINE_AA)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()